compile:
	javac *.java

n1:
	java Node 1
	
n2:
	java Node 2

n3:
	java Node 3

n4:
	java Node 4

n5:
	java Node 5
	
n6:
	java Node 6
	
n7:
	java Node 7
	
n8:
	java Node 8

n9:
	java Node 9

n10:
	java Node 10

n11:
	java Node 11
	
n12:
	java Node 12
	
n13:
	java Node 13
	
n14:
	java Node 14
	
n15:
	java Node 15

clean:
	rm *.class
	rm *.txt
	rm 1/*.txt
	rm 2/*.txt
	rm 3/*.txt
	rm 4/*.txt
	rm 5/*.txt
	rm 6/*.txt
	rm 7/*.txt
	rm 8/*.txt
	rm 9/*.txt
	rm 10/*.txt
	rm 11/*.txt
	rm 12/*.txt
	rm 13/*.txt
	rm 14/*.txt
	rm 15/*.txt

